datasets:
  train:
    type: xgaze
    dir: /work/s-uesaka/xgaze_224_cam12_augmented/train
    batch_size: 50
    split_file: null
  validation:
    type: mpii_normalized
    dir: /work/s-uesaka/MPIIFaceGaze_normalized_h5
    batch_size: 50
    split_file: null
training_parameters:
  batch_size: 20
  epochs: 30
  init_lr: 0.0001
  lr_patience: 10
  lr_decay_factor: 0.1
wandb_config:
  project_name: Gaze_Augmentation Cam12
  run_name: No Augmentation / MPII
random_seed: 0
gpus_list: [0]